export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Education } from './Education'
export { default as Experience } from './Experience'
export { default as Hero } from './Hero'
export { default as Navbar } from './Navbar'
export { default as Skills } from './Skills'
